### PR TITLE
Add MQTT support

### PR DESCRIPTION
**Pull request by jmadden91**
Thanks again for your work on this project. I've finally got around to writing a python script to output the raw data to MQTT, which I use to integrate with home assistant, as I use its energy monitoring dashboard for visualization rather than grafana. 
Example here if you're interested. [https://demo.home-assistant.io/#/energy](url)

Credit to this project, its basically just a re-write in python so it integrates better with your software. 
[https://github.com/heytensai/rpi-power-monitor-mqtt](url)

I've kept the setup in the config.toml file to make it as user friendly as possible. Will require the addition of the below block. 

> [mqtt_broker]
> host = "192.168.x.x"
> username = "username"
> password = "password"
> prefix = "powermon"
> refresh = 5 # Refresh rate in seconds

I run the mqtt.py script as a separate service, but it would be better to implement it similar to your plotting.py script. Or even just adding the publish_message function directly to the main program as having this script query the database just to then output data over mqtt is somewhat double handling. 

For your consideration anyway. 
Cheers

### CODE REVIEW

**Comment by David00** [comment]
Hi @jmadden91, thanks for opening this PR! This looks like a great start to adding MQTT support.  

I agree that it would be better to integrate this more closely with the main body of the function so that the data can be exported to the MQTT broker around the same time that it is created, rather than querying the database.  I'm also thinking this would be an ideal use-case for kicking of a plugin system like I've been wanting to do, where this MQTT integration is treated as a plugin that can be configured and kicked off on the initial program startup.  I was also thinking of a way to simply plug what you've written into the main program body, like you've suggested, and while that would work perfectly well, I don't think it's scalable in terms of an overall plugin ecosystem.

So, I'd like to kick off this integration by refactoring a few parts of the RPiPowerMonitor class and main routine, so that it can better support this MQTT functionality (and future plugins). 

I'll open a new branch and work on some of these changes, and then we can get back to this integration.  Some things that will need to change to fit into what I'm thinking are:

* Moving your `mqtt.py` (and any supporting files) into a mqtt folder, with an empty __init__.py file in the same folder to allow it to be imported
* In order to start the MQTT routine as a child thread, your while True loop will have to go inside a function. 
* Instead of querying the database, I'll add a sharable object that the child thread (your while true loop) can access to get the latest data.  It will likely be the [`results` dictionary](https://github.com/David00/rpi-power-monitor/blob/master/rpi_power_monitor/power_monitor.py#L783) that gets created in `calculate_power()`

Also, is the `mosquitto-clients==2.0.11` in `requirements.txt` necessary? I can't find any details about that library, and it looks like the mosquitto broker interaction is done outside of Python, in the OS environment, via subprocess.run()

**Comment by jmadden91** [comment]
Hey mate, thanks for the feedback. 

I've removed all influx calls now and implemented it directly as some imported functions in the main program. It sends the whole "results" dictionary to the format_data function that extracts the variable names and publishes. I've also added a mqtt enabled check in the config.toml. So the main program won't call the mqtt script if not required. 

> [mqtt_broker]
> enabled = true
> host = "192.168.x.x"
> username = "username"
> password = "password"
> prefix = "powermon"

Just working on formatting the topics now and seeing if I can pull some of your calculated variables like home_load and net etc. 


image

**Comment by jmadden91** [comment]
Few more changes to fix a problem I was having with the working directory not being able to find the config.toml file. Also experimented with setting up a class instead, but I couldn't get it working.

**Comment by jmadden91** [comment]
Ok I've moved the function call that sends the data to mqtt into the queue_for_influx function, which allows me to send the same calculated average values to mqtt that you send to influx. This also allows the home_load, average and net points to be sent. It would probably be cleaner to make a separate function for the mqtt prep rather than use the queue_for_influx, or maybe rename the function to something like prepare_data and use it for all data that will be exported from the program.

Here is how the mqtt output structure now looks. I've dropped pf from the homeload, net and solar topics. 

image

**Comment by David00** [comment]
Awesome @jmadden91. I am working on setting up a plugin system so that this MQTT integration can be used as a plugin, instead of editing the main power monitor program to have MQTT built in.

I still do intend on merging your PR into the project, but please allow me some time to build and test this plugin system. Unfortunately this means we'll need to refactor your PR some more to fit it into this new system, but I think having a plugin system setup is the best for future proofing integrations like this.  I'll follow up once I get the basic system working, at which point I'll push my work to a new branch.

I'm building an example plugin that will trigger a GPIO pin state based on values from the power monitor results, which may be useful for some people to expand on. The actual functionality will be pretty basic because the main purpose is to serve as an example of how to integrate a plugin. 

So far, I've taken the approach of providing the plugin configuration from `config.toml` directly to the plugin, and also making the power monitor results available (including the home load, solar, and net figures), so that you won't need to worry about importing or loading any of that stuff.

**Comment by jmadden91** [comment]
That sounds great mate, cheers. Definitely no rush, I've just been using this to help learn my way around python, still very new to this. Thanks again for this project.

**Comment by David00** [comment]
Hi @jmadden91, I've just about finished the initial version of the new plugin system, and I just pushed my work to a new branch:

https://github.com/David00/rpi-power-monitor/tree/develop/v0.3.0-plugins

I wrote an example plugin that has very basic functionality so you and future developers can reference (along with documentation TBD...) to write plugins.  You can see the example [here](https://github.com/David00/rpi-power-monitor/blob/develop/v0.3.0-plugins/rpi_power_monitor/plugins/gpio_controller_example_plugin/gpio_controller_example_plugin.py).

Here is a quick overview - all of these concepts will go into the documentation that I'll write in the near future, but I wanted to give you something to start with:

1. Your plugin configuration can go directly into the same config.toml, as a new table, like this.  The name of the table should be `[plugins.YOUR_PLUGIN_NAME]`

    ```toml
    ###########
    # PLUGINS #
    ###########

    [plugins.gpio_controller_example_plugin]
    # Mandatory Config Variables
    enabled = true

    # Plugin Specific Config Variables
    pin_numbering_scheme = 'BCM'
    output_pin = 17
    input_pin = 27
    ```

    The plugin configuration will be provided to your plugin by the power monitor controller, so you don't have to worry about loading it from the file or anything. You can assume it will be present in your plugin.


2. Create a new folder inside the plugins/ folder that matches the `YOUR_PLUGIN_NAME` part of the plugin config.
3. Inside this new folder, create a file like `YOUR_PLUGIN_NAME.py`.  It is a requirement that `YOUR_PLUGIN_NAME` is identical in the config.toml, new folder name, and file name. 

4. Below is a stripped down plugin template that shows the structure of everything that you should have in your plugin. Please review the [`gpio_controller_example_plugin.py`](https://github.com/David00/rpi-power-monitor/blob/develop/v0.3.0-plugins/rpi_power_monitor/plugins/gpio_controller_example_plugin/gpio_controller_example_plugin.py) file for some more detailed guidance about the function definitions, their parameters, and accessing values from the `data` and `config` variables.

```python

from time import sleep 

def start_plugin(data, stop_flag, config, logger, *args, **kwargs):

    while not stop_flag.is_set():        
        # Do plugin work here, and then ideally, sleep until you want your plugin to run again.
        # See the contents of the gpio_controller_example_plugin.py file for the complete structure of `data`
       
    stop_plugin()
    return


def stop_plugin():

    # Do plugin cleanup work here
    return
```

The power monitor will call your `start_plugin()` function just before launching the power monitor sampling/calculation loop.  Your plugin can stay running until the power monitor gives the signal to stop.  When that happens (via the user's Ctrl-c or systemctl stop), the power monitor will set the `stop_flag` so that your plugin knows that it's time to stop running and can perform any shutdown/cleanup routines that you need it to.  

In general, your plugin should not sleep for more than 5 seconds at a time _without checking the `stop_flag`_. The reasoning behind this is that if the user stops the power monitor, but a plugin has a long sleep timer for many minutes, the plugin won't break out of the loop until _after_ the sleep timer is over. And by this time, the user has already likely force-terminated the power monitor, leaving your plugin in a potentially unclean state. So, to sleep for any duration longer than 5 seconds, you could do the following:

```python

while not stop_flag.is_set():
    # do work here
    # sleep for 300 seconds

    seconds = 300
    for i in range(0, seconds, 5):
        if stop_flag.is_set():
            break
        if (i + 5) < seconds:
            sleep(5)
        else:
            sleep(seconds - i)
```

I intend on providing this functionality through a wrapper function called `sleep_for(300)` so you don't have to worry about breaking up the sleep duration and checking the flag in your plugin... but that will come later.

The power monitor will **not** attempt to restart your plugin if it crashes, so you should have enough error handling integrated to handle various issues that your plugin might encounter.

Another note - you should not `pop()` any values from the `data` dictionary. This is because all plugins will be expected to share the `data` dictionary.  On that same note, you should also not write to the `data` dictionary - doing so is pointless because it will be updated and overwritten by the main power monitor process fairly quickly (updates happen in under 1s intervals).

Feel free to ask if you have any questions or run into problems refactoring your MQTT code!

**Comment by jmadden91** [comment]
Thats great mate, thanks for the quick turnaround with this. The data dictionary has made it much simpler to structure the data for MQTT. I've added my plugin as mqtt.py and it works as expected. I'll probably improve error handling etc down the track but its fully functional now. Cheers

**Comment by David00** [comment]
Awesome! I will check it out this week. 

I will likely want to have all of the commits squashed (easier to review and track) and rebased onto the new v0.3.0-plugins branch just to keep the history clean.  I can help with the git commands to do all this if needed.

**Pull request closed without merging**
