### PR TITLE
Develop v0.3.0

### PR DESCRIPTION
**Pull request by nightcustard**
Would you please consider adding one or more low rate GPIO inputs to the acquisition scheme to permit sampling of switch open/closed events.  In my case, I would like to monitor relay contacts which close when off-peak power is being supplied.  I currently use modified power-monitor code but it would be brilliant if such a capability was available in the released code.

### CODE REVIEW

**Comment by David00** [comment]
Hi @nightcustard, I'm certainly open to adding this as there are plenty of available GPIOs for use alongside this project.  

It looks like you opened this pull request with no modifications of your own. Did you want to share your modifications for review?

**Comment by nightcustard** [comment]
Hi David - apologies, it appears I used the wrong vehicle for my
suggestion. I do have some code but it's a bit clunky and I have to confess
I don't know GitHub well(!) I'll have a look at other PRs to work out what
to do 😁

Cheers Mike

**Comment by nightcustard** [comment]
As stated above - I shouldn't have raised a PR without code(!).  My bad.  Closing the request.

**Comment by David00** [comment]
Hi @nightcustard, no problem at all! GitHub can be clunky at times :)

In general, a PR is for when you want to contribute your own code to the project. The high level process is that you'd fork the project into your own repository, checkout a new branch (from the latest development branch, which is currently `develop-v0.3.0`), make your changes on your branch, and then create the pull request for the project maintainer to review.  [Here is some additional info](https://blog.mergify.com/understanding-the-github-pull-request-workflow/).

I think for now, it would be best to [open a Discussion](https://github.com/David00/rpi-power-monitor/discussions/new/choose) so we can brainstorm ideas and get an understanding of not only your specific use case, but how others might want to use this as well.

**Pull request closed without merging**
